### ISSUE TITLE
Cert revoked on chocolatey.org

### ISSUE THREAD

**Issue by saminaltamimi** [chocolatey/home#323]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

![image](https://github.com/chocolatey/home/assets/139174515/4123c5f3-b93d-4aed-90ec-93cf84e00a9c)
![image](https://github.com/chocolatey/home/assets/139174515/4a7f25bb-097a-46ce-8edd-fa7175807ed5)

### What is Expected?

I expect to be sent to the chocolatey home page.

### How Did You Get This To Happen?

1. go to chocolatey.org

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
n/a
```

### Output Log

```bash
n/a
```

```[tasklist]
### Tasks
```

**Comment by saminaltamimi** [comment]
Same thing with community.chocolatey.org
![image](https://github.com/chocolatey/home/assets/139174515/ad78aee5-b243-4800-b331-668a7e99a1d1)
![image](https://github.com/chocolatey/home/assets/139174515/8a4e15e8-197d-466e-9953-e378e2b9b573)

**Comment by JPRuskin** [comment]
Thank you for letting us know. We're investigating and trying to fix this immediately.

**Comment by pauby** [comment]
Thanks for raising the issue.

There is a bit of a back-story to this, which I won't bore you with. To give a little context, we were made aware that GoDaddy had made a mistake on our certificate late on Friday, and the revocation was to take place after 72 hours (tomorrow). By that time, we would have a new certificate and this issue would never have appeared. It seems like the revocation was performed early.

As a TL;DR, we are aware of this, we're as unhappy as you are, and we are working on this right now.

**Comment by pauby** [comment]
This has now been resolved. Thank you for your patience in this. We apologise for any inconvenience.

**Comment by saminaltamimi** [comment]
> Thanks for raising the issue.
> 
> There is a bit of a back-story to this, which I won't bore you with. To give a little context, we were made aware that GoDaddy had made a mistake on our certificate late on Friday, and the revocation was to take place after 72 hours (tomorrow). By that time, we would have a new certificate and this issue would never have appeared. It seems like the revocation was performed early.
> 
> As a TL;DR, we are aware of this, we're as unhappy as you are, and we are working on this _right now_.

Personally, I'm not a big fan of GoDaddy and choose to use certbot and Let's Encrypt. But personal politics aside, thanks for the information and speedy resolution.
